# Generated by Django 5.0.2 on 2024-02-24 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('published_at', models.DateTimeField(default=datetime.datetime(2024, 2, 24, 19, 48, 9, 410900), verbose_name='Опубликовать в')),
                ('photo', models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
