# Generated by Django 5.0.2 on 2024-02-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0003_event_institute_project_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
