# Generated by Django 5.0.2 on 2024-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0004_article_photo_event_photo_news_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото'),
        ),
    ]
