# Generated by Django 5.0.2 on 2024-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0006_carouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='Заголовок по умолчанию', max_length=100),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='photo_for_news/'),
        ),
    ]
