# Generated by Django 5.0.2 on 2024-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0007_remove_carouselimage_alt_text_carouselimage_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photo_for_news/')),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
