# Generated by Django 5.0.2 on 2024-03-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0008_carouselitem_delete_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото')),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
