# Generated by Django 5.0.2 on 2024-03-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0011_alter_slideshowimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshowimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='order',
        ),
    ]
