# Generated by Django 5.0.2 on 2024-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0012_alter_slideshowimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_for_news/')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SlideshowImage',
        ),
    ]
