# Generated by Django 5.0.2 on 2024-03-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0014_alter_slide_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideEvent',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kaznitu.slide')),
            ],
            bases=('kaznitu.slide',),
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='caption',
            new_name='description',
        ),
    ]
