# Generated by Django 5.0.2 on 2024-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0015_slideevent_rename_caption_slide_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_for_news/', verbose_name='Путь к фото'),
        ),
    ]
