# Generated by Django 5.0.2 on 2024-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0017_aboutsection_delete_slideevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='AboutUs',
        ),
    ]
