# Generated by Django 5.0.2 on 2024-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznitu', '0018_rename_aboutsection_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='Заголовок', max_length=100),
        ),
    ]
